config/routes.rb
Rails.application.routes.draw do
  
  resources :pictures
  resources :registries
  resources :users
  
  root 'users#index'
  get'users/list_registries/:id', to: 'users#list_registries', as: 'list_registries_user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :registry
end

app/models/registry.rb
class Registry < ApplicationRecord
  belongs_to :user
  has_one :picture
end

app/models/user.rb
class User < ApplicationRecord
    has_many :registries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:base64Picture, :registry_id)
    end
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: [:show, :edit, :update, :destroy]

  # GET /registries
  # GET /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new

    @users = []

    response = RestClient.get 'https://proyectofinal.planodelta.digital/api/usuarios'
    json = JSON.parse response
    
    if !json.nil?
      json.map do |usuario|
        puts usuario["id"]
        @users << User.new(id: "#{usuario["id"]}", userName: "#{usuario["nombreUsuario"]}", password: "#{usuario["password"]}", admin: "#{usuario["admin"]}")
      end
    end

  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.new(registry_params)

    RestClient.post 'https://proyectofinal.planodelta.digital/api/usuarios', @registry.to_json, {content_type: :json, accept: :json}

    redirect_to action: "new"
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registry_params
      params.require(:registry).permit(:name, :educationLevel, :latitude, :longitude, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = []

    response = RestClient.get 'https://proyectofinal.planodelta.digital/api/usuarios'
    json = JSON.parse response
    
    if !json.nil?
      json.map do |usuario|
        puts usuario["id"]
        @users << User.new(id: "#{usuario["id"]}", userName: "#{usuario["nombreUsuario"]}", password: "#{usuario["password"]}", admin: "#{usuario["admin"]}")
      end
    end
    
  end

  def list_registries

    
    @registries = []
    
    response = RestClient.get 'https://proyectofinal.planodelta.digital/api/usuarios/'+params[:id]+'/formularios'
    json = JSON.parse response
    
    if !json.nil?
      json.map do |registro|
        puts registro["id"]
        registry = Registry.new(id: "#{registro["id"]}", name: "#{registro["name"]}", educationLevel: "#{registro["educationLevel"]}", latitude: "#{registro["latitude"]}", longitude: "#{registro["longitude"]}")
        if !registro["foto"].nil?
          picture = Picture.new(id:  "#{registro["foto"]["id"]}", base64Picture: "#{registro["foto"]["fotoBase64"]}", registry: registry)
        end
        @registries << registry
        
        # User.create(id: "#{usuario["id"]}", userName: "#{usuario["nombreUsuario"]}", password: "#{usuario["password"]}", admin: "#{usuario["admin"]}")
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:userName, :password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <div class="container">
    <head>
      <title>Railsrestapp</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :base64Picture %>
    <%= form.text_area :base64Picture %>
  </div>

  <div class="field">
    <%= form.label :registry_id %>
    <%= form.text_field :registry_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Base64picture</th>
      <th>Registry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.base64Picture %></td>
        <td><%= picture.registry_id %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Base64picture:</strong>
  <%= @picture.base64Picture %>
</p>

<p>
  <strong>Registry:</strong>
  <%= @picture.registry_id %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/registries/_form.html.erb
<%= form_with(model: registry, local: true) do |form| %>
  <% if registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
        <% registry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :educationLevel, "Nivel escolar" %>
    <%= form.select :educationLevel, ['Básico', 'Medio', 'Grado Universitario', 'Postgrado', 'Doctorado'], {},{ class: "form-control"} %>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label :latitude, "Latitud" %>
        <%= form.text_field :latitude, class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :longitude, "Longitud" %>
        <%= form.text_field :longitude, class: "form-control" %>
      </div>
    </div>
  </div>



  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.select :user_id, @users.pluck(:userName, :id), {},{ class: "form-control"} %>
    
  </div>

  <div class="actions" style="float:left">
    <%= form.submit "Registrar formulario", class: "btn btn-success" %>
  </div>

    <div style="float:right">
      <%= link_to 'Listado de usuarios', users_path, {class: "btn btn-info"} %>
    </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Editing Registry</h1>

<%= render 'form', registry: @registry %>

<%= link_to 'Show', @registry %> |
<%= link_to 'Back', registries_path %>

app/views/registries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Educationlevel</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registries.each do |registry| %>
      <tr>
        <td><%= registry.name %></td>
        <td><%= registry.educationLevel %></td>
        <td><%= registry.latitude %></td>
        <td><%= registry.longitude %></td>
        <td><%= registry.users_id %></td>
        <td><%= link_to 'Show', registry %></td>
        <td><%= link_to 'Edit', edit_registry_path(registry) %></td>
        <td><%= link_to 'Destroy', registry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registry', new_registry_path %>

app/views/registries/new.html.erb
<h1>Nuevo formulario</h1>

<%= render 'form', registry: @registry %>

app/views/registries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registry.name %>
</p>

<p>
  <strong>Educationlevel:</strong>
  <%= @registry.educationLevel %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @registry.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @registry.longitude %>
</p>

<p>
  <strong>Users:</strong>
  <%= @registry.users_id %>
</p>

<%= link_to 'Edit', edit_registry_path(@registry) %> |
<%= link_to 'Back', registries_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userName %>
    <%= form.text_field :userName %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre de usuario</th>
        <th>Admin</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.userName %></td>
          <td><%= user.admin %></td>
          <td><%= link_to 'Mostrar formularios', list_registries_user_path(user), {class: "btn btn-info"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
  <div>
    <%= link_to 'Nuevo registro', new_registry_path, {class: "btn btn-success"} %>
  </div>

app/views/users/list_registries.html.erb
<h1>Formularios</h1>
  <div>
    <%= link_to 'Listado de usuarios', users_path, {class: "btn btn-info"} %>
  </div>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Nivel Escolar</th>
        <th>Longitud</th>
        <th>Latitud</th>
      </tr>
    </thead>
    <tbody>
      <% @registries.each do |registry| %>
        <tr>
          <td><%= registry.name %></td>
          <td><%= registry.educationLevel %></td>
          <td><%= registry.latitude %></td>
          <td><%= registry.longitude %></td>
        </tr>
        <tr>
            <td colspan="2"><img width=275px; width=270px; src=" <%if !registry.picture.nil?%><%= registry.picture.base64Picture %><% end %>" alt="No hay foto"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.userName %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>